apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  loadBalancerIP: 104.198.25.239
  ports:
  - name: backend-network
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: back