name: Frontend unit testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main
    paths:
    - frontend/**

jobs:
  testing-frontend:
    name: Unit testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
      - name: Clean install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
